const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '..', 'src', 'locales');
const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));

// Use English as fallback structure, override key sections
const langs = {
  id: { name: "Indonesian", common: { loading:"Memuat...",score:"Skor",moves:"Langkah",level:"Level",stars:"Bintang",back:"Kembali",next:"Berikutnya",close:"Tutup",resume:"Lanjutkan",restart:"Mulai Ulang",quit:"Keluar",yes:"Ya",no:"Tidak",ok:"OK",cancel:"Batal",save:"Simpan",settings:"Pengaturan","new":"Baru","continue":"Lanjutkan",bestScore:"Skor terbaik",best:"Terbaik",tapToSkip:"Ketuk untuk lewati",exitApp:"Keluar Aplikasi",exitConfirm:"Apakah Anda yakin ingin keluar?",time:"Waktu",error:"Kesalahan" }, menu:{storyMode:"Mode Cerita",endlessMode:"Mode Tanpa Batas",multiplayer:"Multipemain",achievements:"Pencapaian",leaderboard:"Papan Peringkat",settings:"Pengaturan",selectLevel:"Pilih Level",selectTheme:"Pilih Tema",tagline:"Selamatkan planet, satu kecocokan sekaligus"}, themes:{trashSorting:"Pemilahan Sampah",trashSortingDesc:"Belajar memilah daur ulang!",pollution:"Bersihkan Udara",pollutionDesc:"Singkirkan kendaraan pencemar!",waterConservation:"Konservasi Air",waterConservationDesc:"Hemat air! Setiap tetes berarti.",energyEfficiency:"Efisiensi Energi",energyEfficiencyDesc:"Gunakan energi bersih!",deforestation:"Selamatkan Hutan",deforestationDesc:"Tanam pohon! Lindungi hutan kita."} },
  ru: { name: "Russian", common: { loading:"Загрузка...",score:"Счёт",moves:"Ходы",level:"Уровень",stars:"Звёзды",back:"Назад",next:"Далее",close:"Закрыть",resume:"Продолжить",restart:"Перезапуск",quit:"Выход",yes:"Да",no:"Нет",ok:"ОК",cancel:"Отмена",save:"Сохранить",settings:"Настройки","new":"Новый","continue":"Продолжить",bestScore:"Лучший счёт",best:"Лучший",tapToSkip:"Нажмите чтобы пропустить",exitApp:"Выйти",exitConfirm:"Вы уверены, что хотите выйти?",time:"Время",error:"Ошибка" }, menu:{storyMode:"Режим истории",endlessMode:"Бесконечный режим",multiplayer:"Мультиплеер",achievements:"Достижения",leaderboard:"Таблица лидеров",settings:"Настройки",selectLevel:"Выбрать уровень",selectTheme:"Выбрать тему",tagline:"Спасите планету, одно совпадение за раз"}, themes:{trashSorting:"Сортировка мусора",trashSortingDesc:"Научитесь сортировать!",pollution:"Очистите воздух",pollutionDesc:"Уберите загрязняющие автомобили!",waterConservation:"Сохранение воды",waterConservationDesc:"Берегите воду!",energyEfficiency:"Энергоэффективность",energyEfficiencyDesc:"Используйте чистую энергию!",deforestation:"Спасите леса",deforestationDesc:"Сажайте деревья!"} },
  tr: { name: "Turkish", common: { loading:"Yükleniyor...",score:"Puan",moves:"Hamle",level:"Seviye",stars:"Yıldız",back:"Geri",next:"İleri",close:"Kapat",resume:"Devam Et",restart:"Yeniden Başla",quit:"Çık",yes:"Evet",no:"Hayır",ok:"Tamam",cancel:"İptal",save:"Kaydet",settings:"Ayarlar","new":"Yeni","continue":"Devam Et",bestScore:"En iyi puan",best:"En İyi",tapToSkip:"Atlamak için dokun",exitApp:"Çıkış",exitConfirm:"Çıkmak istediğinizden emin misiniz?",time:"Süre",error:"Hata" }, menu:{storyMode:"Hikaye Modu",endlessMode:"Sonsuz Mod",multiplayer:"Çok Oyunculu",achievements:"Başarılar",leaderboard:"Sıralama",settings:"Ayarlar",selectLevel:"Seviye Seç",selectTheme:"Tema Seç",tagline:"Gezegeni kurtar, tek seferde bir eşleşme"}, themes:{trashSorting:"Çöp Ayırma",trashSortingDesc:"Geri dönüşümü öğrenin!",pollution:"Havayı Temizle",pollutionDesc:"Kirletici araçları kaldırın!",waterConservation:"Su Tasarrufu",waterConservationDesc:"Su tasarrufu yapın!",energyEfficiency:"Enerji Verimliliği",energyEfficiencyDesc:"Temiz enerji kullanın!",deforestation:"Ormanları Kurtar",deforestationDesc:"Ağaç dikin!"} },
  vi: { name: "Vietnamese", common: { loading:"Đang tải...",score:"Điểm",moves:"Nước đi",level:"Cấp độ",stars:"Sao",back:"Quay lại",next:"Tiếp",close:"Đóng",resume:"Tiếp tục",restart:"Chơi lại",quit:"Thoát",yes:"Có",no:"Không",ok:"OK",cancel:"Hủy",save:"Lưu",settings:"Cài đặt","new":"Mới","continue":"Tiếp tục",bestScore:"Điểm cao nhất",best:"Cao nhất",tapToSkip:"Nhấn để bỏ qua",exitApp:"Thoát Ứng dụng",exitConfirm:"Bạn có chắc chắn muốn thoát?",time:"Thời gian",error:"Lỗi" }, menu:{storyMode:"Chế độ Câu chuyện",endlessMode:"Chế độ Vô tận",multiplayer:"Nhiều người chơi",achievements:"Thành tựu",leaderboard:"Bảng xếp hạng",settings:"Cài đặt",selectLevel:"Chọn Cấp độ",selectTheme:"Chọn Chủ đề",tagline:"Cứu hành tinh, từng bước một"}, themes:{trashSorting:"Phân loại Rác",trashSortingDesc:"Học cách phân loại tái chế!",pollution:"Làm sạch Không khí",pollutionDesc:"Loại bỏ xe gây ô nhiễm!",waterConservation:"Tiết kiệm Nước",waterConservationDesc:"Tiết kiệm nước!",energyEfficiency:"Hiệu quả Năng lượng",energyEfficiencyDesc:"Sử dụng năng lượng sạch!",deforestation:"Cứu Rừng",deforestationDesc:"Trồng cây!"} },
  th: { name: "Thai", common: { loading:"กำลังโหลด...",score:"คะแนน",moves:"ตาเดิน",level:"ด่าน",stars:"ดาว",back:"กลับ",next:"ถัดไป",close:"ปิด",resume:"ดำเนินต่อ",restart:"เริ่มใหม่",quit:"ออก",yes:"ใช่",no:"ไม่",ok:"ตกลง",cancel:"ยกเลิก",save:"บันทึก",settings:"ตั้งค่า","new":"ใหม่","continue":"ต่อ",bestScore:"คะแนนสูงสุด",best:"ดีที่สุด",tapToSkip:"แตะเพื่อข้าม",exitApp:"ออกจากแอป",exitConfirm:"คุณแน่ใจหรือไม่ว่าต้องการออก?",time:"เวลา",error:"ข้อผิดพลาด" }, menu:{storyMode:"โหมดเนื้อเรื่อง",endlessMode:"โหมดไม่จำกัด",multiplayer:"ผู้เล่นหลายคน",achievements:"ความสำเร็จ",leaderboard:"กระดานผู้นำ",settings:"ตั้งค่า",selectLevel:"เลือกด่าน",selectTheme:"เลือกธีม",tagline:"ช่วยโลก ทีละการจับคู่"}, themes:{trashSorting:"คัดแยกขยะ",trashSortingDesc:"เรียนรู้การคัดแยกรีไซเคิล!",pollution:"ทำความสะอาดอากาศ",pollutionDesc:"กำจัดยานพาหนะที่ก่อมลพิษ!",waterConservation:"อนุรักษ์น้ำ",waterConservationDesc:"ประหยัดน้ำ!",energyEfficiency:"ประสิทธิภาพพลังงาน",energyEfficiencyDesc:"ใช้พลังงานสะอาด!",deforestation:"ช่วยป่าไม้",deforestationDesc:"ปลูกต้นไม้!"} },
  pl: { name: "Polish", common: { loading:"Ładowanie...",score:"Wynik",moves:"Ruchy",level:"Poziom",stars:"Gwiazdki",back:"Wstecz",next:"Dalej",close:"Zamknij",resume:"Wznów",restart:"Restart",quit:"Wyjdź",yes:"Tak",no:"Nie",ok:"OK",cancel:"Anuluj",save:"Zapisz",settings:"Ustawienia","new":"Nowy","continue":"Kontynuuj",bestScore:"Najlepszy wynik",best:"Najlepszy",tapToSkip:"Stuknij aby pominąć",exitApp:"Zamknij aplikację",exitConfirm:"Czy na pewno chcesz wyjść?",time:"Czas",error:"Błąd" }, menu:{storyMode:"Tryb fabularny",endlessMode:"Tryb nieskończony",multiplayer:"Wieloosobowy",achievements:"Osiągnięcia",leaderboard:"Ranking",settings:"Ustawienia",selectLevel:"Wybierz poziom",selectTheme:"Wybierz motyw",tagline:"Ratuj planetę, jedno dopasowanie naraz"}, themes:{trashSorting:"Sortowanie śmieci",trashSortingDesc:"Naucz się segregować!",pollution:"Oczyść powietrze",pollutionDesc:"Usuń zanieczyszczające pojazdy!",waterConservation:"Oszczędzanie wody",waterConservationDesc:"Oszczędzaj wodę!",energyEfficiency:"Efektywność energetyczna",energyEfficiencyDesc:"Używaj czystej energii!",deforestation:"Ratuj lasy",deforestationDesc:"Sadź drzewa!"} },
  nl: { name: "Dutch", common: { loading:"Laden...",score:"Score",moves:"Zetten",level:"Niveau",stars:"Sterren",back:"Terug",next:"Volgende",close:"Sluiten",resume:"Hervatten",restart:"Herstarten",quit:"Stoppen",yes:"Ja",no:"Nee",ok:"OK",cancel:"Annuleren",save:"Opslaan",settings:"Instellingen","new":"Nieuw","continue":"Doorgaan",bestScore:"Beste score",best:"Beste",tapToSkip:"Tik om over te slaan",exitApp:"App afsluiten",exitConfirm:"Weet je zeker dat je wilt stoppen?",time:"Tijd",error:"Fout" }, menu:{storyMode:"Verhaalmodus",endlessMode:"Eindeloze modus",multiplayer:"Multiplayer",achievements:"Prestaties",leaderboard:"Ranglijst",settings:"Instellingen",selectLevel:"Kies niveau",selectTheme:"Kies thema",tagline:"Red de planeet, één match tegelijk"}, themes:{trashSorting:"Afval sorteren",trashSortingDesc:"Leer recyclen!",pollution:"Zuiver de lucht",pollutionDesc:"Verwijder vervuilende voertuigen!",waterConservation:"Waterbesparing",waterConservationDesc:"Bespaar water!",energyEfficiency:"Energie-efficiëntie",energyEfficiencyDesc:"Gebruik schone energie!",deforestation:"Red de bossen",deforestationDesc:"Plant bomen!"} },
  sv: { name: "Swedish", common: { loading:"Laddar...",score:"Poäng",moves:"Drag",level:"Nivå",stars:"Stjärnor",back:"Tillbaka",next:"Nästa",close:"Stäng",resume:"Fortsätt",restart:"Starta om",quit:"Avsluta",yes:"Ja",no:"Nej",ok:"OK",cancel:"Avbryt",save:"Spara",settings:"Inställningar","new":"Ny","continue":"Fortsätt",bestScore:"Bästa poäng",best:"Bästa",tapToSkip:"Tryck för att hoppa över",exitApp:"Avsluta appen",exitConfirm:"Är du säker på att du vill avsluta?",time:"Tid",error:"Fel" }, menu:{storyMode:"Berättelseläge",endlessMode:"Oändligt läge",multiplayer:"Flerspelarläge",achievements:"Prestationer",leaderboard:"Topplista",settings:"Inställningar",selectLevel:"Välj nivå",selectTheme:"Välj tema",tagline:"Rädda planeten, en match i taget"}, themes:{trashSorting:"Sopsortering",trashSortingDesc:"Lär dig att sortera!",pollution:"Rena luften",pollutionDesc:"Ta bort förorenande fordon!",waterConservation:"Vattenbesparing",waterConservationDesc:"Spara vatten!",energyEfficiency:"Energieffektivitet",energyEfficiencyDesc:"Använd ren energi!",deforestation:"Rädda skogarna",deforestationDesc:"Plantera träd!"} }
};

// For each lang, build a full file using en.json as base, overriding with translated sections
for (const [code, data] of Object.entries(langs)) {
  const full = JSON.parse(JSON.stringify(en)); // deep clone en
  for (const [section, vals] of Object.entries(data)) {
    if (section === 'name') continue;
    full[section] = { ...full[section], ...vals };
  }
  const filePath = path.join(localesDir, `${code}.json`);
  fs.writeFileSync(filePath, JSON.stringify(full, null, 4), 'utf8');
  console.log(`Created ${code}.json`);
}
console.log('Done!');
