// Script to generate all 10 new locale files
const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '..', 'src', 'locales');

// Full translations for each new language
const translations = {
  hi: {
    common: { loading: "लोड हो रहा है...", score: "स्कोर", moves: "चालें", level: "स्तर", stars: "सितारे", back: "वापस", next: "अगला", close: "बंद करें", resume: "जारी रखें", restart: "पुनः प्रारंभ", quit: "छोड़ें", yes: "हाँ", no: "नहीं", ok: "ठीक है", cancel: "रद्द करें", save: "सहेजें", settings: "सेटिंग्स", new: "नया", continue: "जारी रखें", bestScore: "सर्वश्रेष्ठ स्कोर", best: "सर्वश्रेष्ठ", tapToSkip: "छोड़ने के लिए टैप करें", exitApp: "ऐप बंद करें", exitConfirm: "क्या आप वाकई बाहर निकलना चाहते हैं?", time: "समय", error: "त्रुटि" },
    menu: { storyMode: "कहानी मोड", endlessMode: "अंतहीन मोड", multiplayer: "मल्टीप्लेयर", achievements: "उपलब्धियाँ", leaderboard: "लीडरबोर्ड", settings: "सेटिंग्स", selectLevel: "स्तर चुनें", selectTheme: "थीम चुनें", tagline: "एक मैच में ग्रह को बचाएं" },
    multiplayer: { title: "मल्टीप्लेयर", createRoom: "कमरा बनाएं", joinRoom: "कमरे में शामिल हों", roomName: "कमरे का नाम", roomNamePlaceholder: "कमरे का नाम दर्ज करें", roomCode: "कमरे का कोड", password: "पासवर्ड", gameMode: "गेम मोड", raceMode: "रेस", timedMode: "समयबद्ध", movesMode: "चालें", targetScore: "लक्ष्य स्कोर", duration: "अवधि", movesLimit: "चाल सीमा", theme: "थीम", enableVoting: "वोटिंग सक्षम करें", players: "खिलाड़ी", host: "होस्ट", voteTheme: "थीम के लिए वोट करें", startGame: "गेम शुरू करें", waitingHost: "होस्ट द्वारा शुरू करने की प्रतीक्षा...", leaveRoom: "कमरा छोड़ें", leaveConfirm: "क्या आप वाकई इस कमरे को छोड़ना चाहते हैं?", activeGames: "सक्रिय गेम", waitingRooms: "प्रतीक्षा कक्ष", completedGames: "पूर्ण गेम", noActiveGames: "कोई सक्रिय गेम नहीं", noWaitingRooms: "कोई प्रतीक्षा कक्ष नहीं", noCompletedGames: "कोई पूर्ण गेम नहीं", noRooms: "अभी तक कोई कमरा नहीं", createOrJoin: "दोस्तों के साथ खेलने के लिए कमरा बनाएं या शामिल हों", liveRankings: "लाइव रैंकिंग", finished: "समाप्त!", results: "परिणाम", winner: "विजेता", yourRank: "आपकी रैंक", finalRankings: "अंतिम रैंकिंग", backToMenu: "मेनू पर वापस", dnf: "DNF", errorRoomName: "कृपया कमरे का नाम दर्ज करें", errorPassword: "पासवर्ड 4-6 अंकों का होना चाहिए", errorTheme: "कृपया थीम चुनें या वोटिंग सक्षम करें", errorCreate: "कमरा बनाने में विफल", errorRoomCode: "कमरे का कोड 6 अक्षर का होना चाहिए", errorJoin: "कमरे में शामिल होने में विफल", errorStart: "गेम शुरू करने में विफल", days: "दिन", hours: "घंटे", minutes: "मिनट", noUnlockedThemes: "थीम अनलॉक करने के लिए कहानी मोड स्तर पूर्ण करें", yourName: "आपका नाम", enterName: "अपना नाम दर्ज करें", gameActive: "प्रगति में", gameComplete: "पूर्ण", you: "आप" },
    game: { paused: "रुका हुआ", levelComplete: "स्तर पूर्ण!", gameOver: "गेम ओवर", nextLevel: "अगला स्तर", playAgain: "फिर से खेलें", backToLevels: "स्तरों पर वापस", mainMenu: "मुख्य मेनू", levels: "स्तर", movesRemaining: "{{count}} चालें शेष", remainingMoves: "शेष चालें", targetScore: "लक्ष्य: {{score}}", newHighScore: "नया उच्च स्कोर!", storyComplete: "कहानी पूर्ण!", congratulations: "बधाई!", completedAllLevels: "आपने MatchWell के सभी {{count}} स्तर पूरे कर लिए!", thankYouPlaying: "खेलने और हमारे ग्रह के बारे में सीखने के लिए धन्यवाद।", collectMoreStars: "और सितारे इकट्ठा करें", replayForStars: "अधिक सितारे अर्जित करने के लिए स्तर दोबारा खेलें!", earnMedals: "पदक अर्जित करें", achievementsPage: "अपनी प्रगति के लिए पदक एकत्र करने के लिए उपलब्धियाँ पृष्ठ पर जाएँ!", tryEndlessMode: "अंतहीन मोड आज़माएं", endlessChallenge: "अंतहीन मोड में खुद को चुनौती दें!", climbLeaderboard: "लीडरबोर्ड पर चढ़ें", competeWorldwide: "दुनिया भर के खिलाड़ियों के साथ प्रतिस्पर्धा करें!", letsGo: "चलो चलें!", comingSoon: "जल्द आ रहा है" },
    tutorial: { howToPlay: "कैसे खेलें", slide1Title: "3 या अधिक मिलाएं", slide1Desc: "एक पंक्ति या स्तंभ में 3 या अधिक समान आइटम का मिलान करने के लिए टाइलों को स्वैप करें।", slide2Title: "लक्ष्य तक पहुंचें", slide2Desc: "स्तर पूरा करने के लिए चालें खत्म होने से पहले पर्याप्त अंक प्राप्त करें।", slide3Title: "पावर-अप्स", slide3Desc: "पावर चार्ज करने के लिए 4+ टाइल मिलाएं। 10+ अंक पर, एक पंक्ति या स्तंभ साफ़ करने के लिए पृथ्वी आइकन पर टैप करें!", slide4Title: "जीतें और सितारे अर्जित करें", slide4Desc: "3 सितारे तक अर्जित करने के लिए शेष चालों के साथ स्तर पूरा करें!", letsPlay: "चलो खेलें!", score: "स्कोर", target: "लक्ष्य", movesLeft: "{{count}} चालें शेष", match4: "4-मैच", match5: "5-मैच", power2: "+2 पावर", power5: "+5 पावर", powerHint: "10+ = एकल पंक्ति • 15 = क्रॉस पैटर्न", starHint: "अधिक चालें = अधिक सितारे" },
    achievements: { title: "उपलब्धियाँ", medals: "पदक", storyMode: "कहानी मोड", starMilestones: "सितारा मील के पत्थर", endlessMode: "अंतहीन मोड", locked: "लॉक", unlocked: "अनलॉक", totalStars: "कुल सितारे", completedLevels: "पूर्ण स्तर" },
    settings: { title: "सेटिंग्स", sound: "ध्वनि", music: "संगीत", backgroundMusic: "पृष्ठभूमि संगीत", sfx: "ध्वनि प्रभाव", tileSounds: "टाइल ध्वनियाँ और प्रतिक्रिया", language: "भाषा", selectLanguage: "भाषा चुनें", restartRequired: "लेआउट बदलाव के लिए ऐप पुनरारंभ आवश्यक", restartNow: "अभी पुनरारंभ करें", restartLater: "बाद में", resetProgress: "प्रगति रीसेट करें", resetAllProgress: "सभी प्रगति रीसेट करें", resetWarning: "यह आपकी सभी प्रगति हटा देगा। क्या आप सुनिश्चित हैं?", testers: "परीक्षक", testersThanks: "आपकी मूल्यवान प्रतिक्रिया के लिए धन्यवाद!", about: "के बारे में", version: "संस्करण", developer: "डेवलपर", sourceCode: "स्रोत कोड", privacy: "गोपनीयता", privacyDesc: "कोई डेटा एकत्र या साझा नहीं किया जाता", credits: "क्रेडिट", privacyPolicy: "गोपनीयता नीति" },
    leaderboard: { title: "लीडरबोर्ड", global: "वैश्विक", weekly: "साप्ताहिक", rank: "रैंक", player: "खिलाड़ी", score: "स्कोर", noData: "अभी तक कोई लीडरबोर्ड डेटा नहीं", yourRank: "आपकी रैंक", notRanked: "रैंक नहीं", joinLeaderboard: "लीडरबोर्ड में शामिल हों", publishMyScore: "मेरा स्कोर प्रकाशित करें", playersWorldwide: "{{count}} दुनिया भर के खिलाड़ी", playersWorldwideLabel: "दुनिया भर के खिलाड़ी", chooseUsername: "अपना उपयोगकर्ता नाम चुनें", usernameShown: "यह लीडरबोर्ड पर दिखाया जाएगा", enterUsername: "उपयोगकर्ता नाम दर्ज करें", join: "शामिल हों", noScoresTitle: "प्रकाशित करने के लिए कोई स्कोर नहीं", noScoresMessage: "लीडरबोर्ड के लिए स्कोर प्राप्त करने के लिए पहले अंतहीन मोड खेलें!", successTitle: "सफलता!", successMessage: "आपका स्कोर लीडरबोर्ड पर प्रकाशित हो गया!", errorTitle: "त्रुटि", publishFailed: "स्कोर प्रकाशित करने में विफल", pleaseEnterUsername: "कृपया उपयोगकर्ता नाम दर्ज करें", usernameTooShort: "उपयोगकर्ता नाम कम से कम 3 अक्षर का होना चाहिए", usernameNotAvailable: "उपयोगकर्ता नाम उपलब्ध नहीं है", registrationFailed: "पंजीकरण विफल", you: "(आप)", pts: "अंक", perMove: "/चाल" },
    themes: { trashSorting: "कचरा छँटाई", trashSortingDesc: "रीसाइक्लेबल्स को छाँटना सीखें!", pollution: "हवा साफ़ करें", pollutionDesc: "हमारे शहरों को साफ़ करने के लिए प्रदूषण कारी वाहनों को हटाएं!", waterConservation: "जल संरक्षण", waterConservationDesc: "पानी बचाएं! हर बूंद मायने रखती है।", energyEfficiency: "ऊर्जा दक्षता", energyEfficiencyDesc: "स्वच्छ ऊर्जा का उपयोग करें!", deforestation: "वनों को बचाएं", deforestationDesc: "पेड़ लगाएं! भविष्य की पीढ़ियों के लिए वनों की रक्षा करें।" },
    endless: { noMoveLimit: "कोई चाल सीमा नहीं — बस मिलाते रहें और अपना उच्च स्कोर तोड़ें!" },
    themeAchievements: { recycler: "रीसाइक्लर", recyclerDesc: "सभी कचरा छँटाई स्तर पूरे करें", cleanAirChampion: "वायु शोधक", cleanAirChampionDesc: "सभी प्रदूषण स्तर पूरे करें", waterGuardian: "जल संरक्षक", waterGuardianDesc: "सभी जल संरक्षण स्तर पूरे करें", energySaver: "ऊर्जा बचतकर्ता", energySaverDesc: "सभी ऊर्जा दक्षता स्तर पूरे करें", forestProtector: "वन रक्षक", forestProtectorDesc: "सभी वनों की कटाई स्तर पूरे करें" },
    starAchievements: { bronzeCollector: "कांस्य संग्राहक", bronzeCollectorDesc: "30 कुल सितारे अर्जित करें", silverCollector: "रजत संग्राहक", silverCollectorDesc: "60 कुल सितारे अर्जित करें", goldCollector: "स्वर्ण संग्राहक", goldCollectorDesc: "90 कुल सितारे अर्जित करें", diamondCollector: "हीरा संग्राहक", diamondCollectorDesc: "120 कुल सितारे अर्जित करें", starMaster: "सितारा मास्टर", starMasterDesc: "सभी 150 सितारे अर्जित करें" },
    endlessTiers: { bronze: "कांस्य", silver: "रजत", gold: "स्वर्ण", diamond: "हीरा", earthSaver: "पृथ्वी रक्षक" },
    climate: { timeLeft: "तापमान वृद्धि को 1.5°C तक सीमित करने के लिए शेष समय" },
    facts: {
      trash: ["एक एल्युमीनियम कैन रीसाइक्लिंग से 3 घंटे टीवी चलाने जितनी ऊर्जा बचती है!", "कागज को 5-7 बार रीसाइक्ल किया जा सकता है!", "कांच 100% रीसाइक्ल योग्य है!", "लैंडफिल में जैविक कचरा मीथेन पैदा करता है!", "उचित कचरा छँटाई से घरेलू कचरा 80% तक कम हो सकता है!", "दुनिया हर साल 350 मिलियन टन से अधिक प्लास्टिक कचरा पैदा करती है!", "एक प्लास्टिक की बोतल को विघटित होने में 500 साल लगते हैं!", "खाद्य अपशिष्ट की कम्पोस्टिंग मीथेन उत्सर्जन को काफी कम करती है!", "ई-कचरा दुनिया की सबसे तेजी से बढ़ने वाली कचरा धारा है!", "वैश्विक रूप से, उत्पादित सभी प्लास्टिक का केवल 9% रीसाइक्ल किया गया है!"],
      pollution: ["परिवहन वैश्विक ग्रीनहाउस गैस उत्सर्जन का लगभग 16% है!", "इलेक्ट्रिक वाहन शून्य प्रत्यक्ष उत्सर्जन करते हैं!", "ड्राइविंग के बजाय साइकिल चलाना आपके कार्बन फुटप्रिंट को काफी कम कर सकता है!", "सार्वजनिक परिवहन निजी कारों की तुलना में 50% कम ईंधन उपयोग करता है!", "पेड़ लगाने से CO2 अवशोषित होती है!", "वायु प्रदूषण हर साल दुनिया भर में 70 लाख समय से पहले मौतों का कारण बनता है!", "ड्राइविंग के बजाय चलने से प्रति किलोमीटर लगभग 0.2 किग्रा CO2 बचती है!", "कारपूलिंग से आपका उत्सर्जन आधा हो जाता है!", "रिमोट वर्क आपके कार्बन फुटप्रिंट को 54% तक कम कर सकता है!", "शहरों में हरित स्थान शहरी तापमान को 5°C तक कम कर सकते हैं!"],
      water: ["पृथ्वी का केवल 3% पानी मीठा पानी है!", "ब्रश करते समय नल बंद करने से रोजाना 30 लीटर पानी बचता है!", "एक टपकने वाला नल प्रति वर्ष 11,000 लीटर से अधिक पानी बर्बाद कर सकता है!", "छोटे शावर प्रति माह 550 लीटर तक पानी बचा सकते हैं!", "वर्षा जल संचयन से घरेलू पानी का उपयोग 50% कम हो सकता है!", "कृषि विश्व की 70% मीठे पानी की आपूर्ति का उपयोग करती है!", "एक टपकने वाला नल एक सप्ताह में बाथटब भरने जितना पानी बर्बाद कर सकता है!", "कम प्रवाह वाले शावरहेड सालाना 10,000 लीटर पानी बचा सकते हैं!", "दुनिया भर में दो अरब लोगों को सुरक्षित पेयजल नहीं मिलता!", "पानी जीवन का सार है - संरक्षण हमारा भविष्य सुनिश्चित करता है!"],
      energy: ["LED बल्ब पारंपरिक इंकैंडेसेंट लाइटिंग की तुलना में 75% कम ऊर्जा उपयोग करते हैं!", "सौर पैनल बिजली के बिल को 50% से 100% तक कम कर सकते हैं!", "पवन ऊर्जा दुनिया को 18 गुना बिजली दे सकती है!", "उपयोग में न होने पर उपकरणों को अनप्लग करने से बिजली पर 10% बचत हो सकती है!", "ऊर्जा-कुशल उपकरण यूटिलिटी बिलों को 30% तक कम कर सकते हैं!", "नवीकरणीय ऊर्जा जीवाश्म ईंधन की तुलना में 3 गुना अधिक नौकरियां पैदा करती है!", "एक पवन टर्बाइन 500 घरों तक को बिजली दे सकती है!", "स्मार्ट थर्मोस्टैट हीटिंग और कूलिंग लागत पर 10-15% बचा सकते हैं!", "सौर ऊर्जा दुनिया भर में सबसे तेजी से बढ़ने वाला बिजली स्रोत है!", "बैटरियाँ स्वच्छ ऊर्जा के भंडारण की कुंजी हैं!"],
      forest: ["वन पृथ्वी की 80% स्थलीय जैव विविधता का घर हैं!", "एक पेड़ प्रति वर्ष लगभग 22 किग्रा CO2 अवशोषित कर सकता है!", "हम हर साल विश्व स्तर पर 10 मिलियन हेक्टेयर वन खो देते हैं!", "पेड़ लगाना जलवायु परिवर्तन से लड़ने के सबसे प्रभावी तरीकों में से एक है!", "वन ऑक्सीजन, स्वच्छ पानी और वन्य जीवन के लिए घर प्रदान करते हैं!", "बांस 24 घंटे में 1 मीटर तक बढ़ सकता है!", "वन बहाली दशकों में खोई जैव विविधता को वापस ला सकती है!", "पुराने वन युवा वनों की तुलना में अधिक कार्बन संग्रहित करते हैं!", "रीसाइक्ल फाइबर से बना कागज प्रति टन 17 पेड़ बचाता है!", "वनों की रक्षा करना हमारे भविष्य की रक्षा करना है!"]
    },
    localMultiplayer: { title: "स्थानीय खेल", localPlay: "स्थानीय खेल (ब्लूटूथ/वाईफ़ाई)", description: "ब्लूटूथ या वाईफ़ाई डायरेक्ट का उपयोग करके पास के दोस्तों के साथ खेलें - इंटरनेट की आवश्यकता नहीं!", hostGame: "गेम होस्ट करें", hostDescription: "गेम बनाएं और दोस्तों के शामिल होने की प्रतीक्षा करें", findGame: "गेम खोजें", findDescription: "शामिल होने के लिए आसपास के गेम खोजें", searching: "आसपास गेम खोज रहे हैं...", tapToJoin: "शामिल होने के लिए टैप करें", noGamesFound: "अभी तक कोई गेम नहीं मिला", noGamesHint: "सुनिश्चित करें कि होस्ट का गेम पास में चल रहा है", permissionRequired: "अनुमति आवश्यक", permissionMessage: "स्थानीय मल्टीप्लेयर के लिए ब्लूटूथ और स्थान अनुमतियाँ आवश्यक हैं।", lobby: "गेम लॉबी", waitingRoom: "प्रतीक्षा कक्ष", waitingForPlayers: "खिलाड़ियों की प्रतीक्षा...", settingUp: "सेटअप हो रहा है...", connectedToHost: "होस्ट से जुड़ा", connecting: "कनेक्ट हो रहा है...", players: "खिलाड़ी", you_host: "आप (होस्ट)", you: "आप", disconnected: "डिस्कनेक्ट", gameSettings: "गेम सेटिंग्स", startGame: "गेम शुरू करें", waitingForHost: "होस्ट द्वारा शुरू करने की प्रतीक्षा...", waitForPlayers: "खिलाड़ियों की प्रतीक्षा करें", needOnePlayer: "शुरू करने से पहले कम से कम एक खिलाड़ी को शामिल होना होगा।", showScoreboard: "स्कोरबोर्ड", hideScoreboard: "छिपाएं", results: "परिणाम", gameOver: "गेम ओवर!", noResults: "कोई परिणाम उपलब्ध नहीं", playAgain: "फिर से खेलें", backToMenu: "मेनू पर वापस", hardwareReminder: "स्थिर कनेक्शन के लिए कृपया सुनिश्चित करें कि Wi-Fi, ब्लूटूथ, और स्थान सेवाएँ सक्षम हैं।" }
  },
  pt: {
    common: { loading: "Carregando...", score: "Pontuação", moves: "Movimentos", level: "Nível", stars: "Estrelas", back: "Voltar", next: "Próximo", close: "Fechar", resume: "Continuar", restart: "Reiniciar", quit: "Sair", yes: "Sim", no: "Não", ok: "OK", cancel: "Cancelar", save: "Salvar", settings: "Configurações", new: "Novo", continue: "Continuar", bestScore: "Melhor pontuação", best: "Melhor", tapToSkip: "Toque para pular", exitApp: "Sair do App", exitConfirm: "Tem certeza que deseja sair?", time: "Tempo", error: "Erro" },
    menu: { storyMode: "Modo História", endlessMode: "Modo Infinito", multiplayer: "Multijogador", achievements: "Conquistas", leaderboard: "Classificação", settings: "Configurações", selectLevel: "Selecionar Nível", selectTheme: "Selecionar Tema", tagline: "Salve o planeta, uma combinação de cada vez" },
    multiplayer: { title: "Multijogador", createRoom: "Criar Sala", joinRoom: "Entrar na Sala", roomName: "Nome da Sala", roomNamePlaceholder: "Digite o nome da sala", roomCode: "Código da Sala", password: "Senha", gameMode: "Modo de Jogo", raceMode: "Corrida", timedMode: "Tempo", movesMode: "Movimentos", targetScore: "Pontuação Alvo", duration: "Duração", movesLimit: "Limite de Movimentos", theme: "Tema", enableVoting: "Ativar Votação", players: "Jogadores", host: "Anfitrião", voteTheme: "Votar no Tema", startGame: "Iniciar Jogo", waitingHost: "Aguardando o anfitrião iniciar...", leaveRoom: "Sair da Sala", leaveConfirm: "Tem certeza que deseja sair desta sala?", activeGames: "Jogos Ativos", waitingRooms: "Salas de Espera", completedGames: "Jogos Completos", noActiveGames: "Sem jogos ativos", noWaitingRooms: "Sem salas de espera", noCompletedGames: "Sem jogos completos", noRooms: "Nenhuma sala ainda", createOrJoin: "Crie ou entre em uma sala para jogar com amigos", liveRankings: "Classificação ao Vivo", finished: "Finalizado!", results: "Resultados", winner: "Vencedor", yourRank: "Sua Posição", finalRankings: "Classificação Final", backToMenu: "Voltar ao Menu", dnf: "DNF", errorRoomName: "Por favor, digite o nome da sala", errorPassword: "A senha deve ter 4-6 dígitos", errorTheme: "Selecione um tema ou ative a votação", errorCreate: "Falha ao criar sala", errorRoomCode: "O código da sala deve ter 6 caracteres", errorJoin: "Falha ao entrar na sala", errorStart: "Falha ao iniciar o jogo", days: "Dias", hours: "Horas", minutes: "Minutos", noUnlockedThemes: "Complete níveis do Modo História para desbloquear temas", yourName: "Seu Nome", enterName: "Digite seu nome", gameActive: "Em Andamento", gameComplete: "Completo", you: "Você" },
    game: { paused: "Pausado", levelComplete: "Nível Completo!", gameOver: "Fim de Jogo", nextLevel: "Próximo Nível", playAgain: "Jogar Novamente", backToLevels: "Voltar aos Níveis", mainMenu: "Menu Principal", levels: "Níveis", movesRemaining: "{{count}} movimentos restantes", remainingMoves: "Movimentos Restantes", targetScore: "Alvo: {{score}}", newHighScore: "Nova Pontuação Máxima!", storyComplete: "História Completa!", congratulations: "Parabéns!", completedAllLevels: "Você completou todos os {{count}} níveis do MatchWell!", thankYouPlaying: "Obrigado por jogar e aprender sobre nosso planeta.", collectMoreStars: "Colete Mais Estrelas", replayForStars: "Rejogue níveis para ganhar mais estrelas!", earnMedals: "Ganhe Medalhas", achievementsPage: "Visite a página de Conquistas para coletar medalhas!", tryEndlessMode: "Tente o Modo Infinito", endlessChallenge: "Desafie-se no Modo Infinito!", climbLeaderboard: "Suba na Classificação", competeWorldwide: "Compita com jogadores do mundo todo!", letsGo: "Vamos!", comingSoon: "Em breve" },
    tutorial: { howToPlay: "Como Jogar", slide1Title: "Combine 3 ou Mais", slide1Desc: "Troque peças para criar combinações de 3 ou mais itens idênticos.", slide2Title: "Alcance o Alvo", slide2Desc: "Marque pontos suficientes antes de ficar sem movimentos.", slide3Title: "Power-Ups", slide3Desc: "Combine 4+ peças para carregar poder. Com 10+ pontos, toque no ícone da Terra!", slide4Title: "Vença e Ganhe Estrelas", slide4Desc: "Complete níveis com movimentos restantes para ganhar até 3 estrelas!", letsPlay: "Vamos Jogar!", score: "Pontuação", target: "Alvo", movesLeft: "{{count}} movimentos restantes", match4: "4-combo", match5: "5-combo", power2: "+2 poder", power5: "+5 poder", powerHint: "10+ = Linha simples • 15 = Padrão cruzado", starHint: "Mais movimentos = Mais estrelas" },
    achievements: { title: "Conquistas", medals: "Medalhas", storyMode: "Modo História", starMilestones: "Marcos de Estrelas", endlessMode: "Modo Infinito", locked: "Bloqueado", unlocked: "Desbloqueado", totalStars: "Total de Estrelas", completedLevels: "Níveis Completos" },
    settings: { title: "Configurações", sound: "Som", music: "Música", backgroundMusic: "Música de fundo", sfx: "Efeitos Sonoros", tileSounds: "Sons de peças", language: "Idioma", selectLanguage: "Selecionar Idioma", restartRequired: "Reinicialização necessária para mudanças de layout", restartNow: "Reiniciar Agora", restartLater: "Depois", resetProgress: "Resetar Progresso", resetAllProgress: "Resetar Todo o Progresso", resetWarning: "Isso excluirá todo o seu progresso. Tem certeza?", testers: "Testadores", testersThanks: "Obrigado pelo seu feedback valioso!", about: "Sobre", version: "Versão", developer: "Desenvolvedor", sourceCode: "Código Fonte", privacy: "Privacidade", privacyDesc: "Nenhum dado é coletado ou compartilhado", credits: "Créditos", privacyPolicy: "Política de Privacidade" },
    leaderboard: { title: "Classificação", global: "Global", weekly: "Semanal", rank: "Posição", player: "Jogador", score: "Pontuação", noData: "Sem dados de classificação ainda", yourRank: "Sua Posição", notRanked: "Sem Classificação", joinLeaderboard: "Entrar na Classificação", publishMyScore: "Publicar Minha Pontuação", playersWorldwide: "{{count}} jogadores no mundo", playersWorldwideLabel: "jogadores no mundo", chooseUsername: "Escolha Seu Nome de Usuário", usernameShown: "Será exibido na classificação", enterUsername: "Digite o nome de usuário", join: "Entrar", noScoresTitle: "Sem Pontuações para Publicar", noScoresMessage: "Jogue o Modo Infinito primeiro para obter pontuações!", successTitle: "Sucesso!", successMessage: "Sua pontuação foi publicada!", errorTitle: "Erro", publishFailed: "Falha ao publicar pontuação", pleaseEnterUsername: "Digite um nome de usuário", usernameTooShort: "O nome de usuário deve ter pelo menos 3 caracteres", usernameNotAvailable: "Nome de usuário não disponível", registrationFailed: "Falha no registro", you: "(Você)", pts: "pts", perMove: "/mov" },
    themes: { trashSorting: "Separação de Lixo", trashSortingDesc: "Aprenda a separar recicláveis!", pollution: "Limpe o Ar", pollutionDesc: "Remova veículos poluentes!", waterConservation: "Conservação da Água", waterConservationDesc: "Economize água! Cada gota conta.", energyEfficiency: "Eficiência Energética", energyEfficiencyDesc: "Use energia limpa!", deforestation: "Salve as Florestas", deforestationDesc: "Plante árvores! Proteja nossas florestas." },
    endless: { noMoveLimit: "Sem limite de movimentos — continue combinando e supere sua pontuação!" },
    themeAchievements: { recycler: "Reciclador", recyclerDesc: "Complete todos os níveis de Separação de Lixo", cleanAirChampion: "Purificador do Ar", cleanAirChampionDesc: "Complete todos os níveis de Poluição", waterGuardian: "Guardião da Água", waterGuardianDesc: "Complete todos os níveis de Conservação da Água", energySaver: "Economizador de Energia", energySaverDesc: "Complete todos os níveis de Eficiência Energética", forestProtector: "Protetor da Floresta", forestProtectorDesc: "Complete todos os níveis de Desmatamento" },
    starAchievements: { bronzeCollector: "Coletor Bronze", bronzeCollectorDesc: "Ganhe 30 estrelas no total", silverCollector: "Coletor Prata", silverCollectorDesc: "Ganhe 60 estrelas no total", goldCollector: "Coletor Ouro", goldCollectorDesc: "Ganhe 90 estrelas no total", diamondCollector: "Coletor Diamante", diamondCollectorDesc: "Ganhe 120 estrelas no total", starMaster: "Mestre das Estrelas", starMasterDesc: "Ganhe todas as 150 estrelas" },
    endlessTiers: { bronze: "Bronze", silver: "Prata", gold: "Ouro", diamond: "Diamante", earthSaver: "Salvador da Terra" },
    climate: { timeLeft: "Tempo restante para limitar o aquecimento a 1,5°C" },
    facts: {
      trash: ["Reciclar uma lata de alumínio economiza energia suficiente para 3 horas de TV!", "O papel pode ser reciclado de 5 a 7 vezes!", "O vidro é 100% reciclável sem perda de qualidade!", "Resíduos orgânicos em aterros produzem metano!", "A separação adequada pode reduzir o lixo doméstico em até 80%!", "O mundo produz mais de 350 milhões de toneladas de resíduos plásticos por ano!", "Uma garrafa plástica leva 500 anos para se decompor!", "Compostar resíduos alimentares reduz significativamente as emissões de metano!", "O lixo eletrônico é o fluxo de resíduos que mais cresce no mundo!", "Apenas 9% de todo o plástico produzido foi reciclado!"],
      pollution: ["O transporte responde por cerca de 16% das emissões globais de gases de efeito estufa!", "Veículos elétricos produzem zero emissões diretas!", "Andar de bicicleta pode reduzir significativamente sua pegada de carbono!", "O transporte público usa 50% menos combustível por passageiro-km!", "Plantar árvores ajuda a absorver CO2!", "A poluição do ar causa 7 milhões de mortes prematuras anualmente!", "Caminhar em vez de dirigir economiza cerca de 0,2 kg de CO2 por km!", "Compartilhar carona reduz suas emissões pela metade!", "O trabalho remoto pode reduzir sua pegada de carbono em até 54%!", "Espaços verdes nas cidades podem reduzir temperaturas urbanas em até 5°C!"],
      water: ["Apenas 3% da água da Terra é doce!", "Fechar a torneira ao escovar os dentes economiza 30 litros por dia!", "Uma torneira pingando pode desperdiçar mais de 11.000 litros por ano!", "Banhos mais curtos economizam até 550 litros por mês!", "A captação de água da chuva pode reduzir o uso doméstico em 50%!", "A agricultura usa 70% do suprimento global de água doce!", "Uma torneira pingando pode encher uma banheira em uma semana!", "Chuveiros de baixo fluxo economizam 10.000 litros anualmente!", "Dois bilhões de pessoas não têm acesso a água potável segura!", "A água é essência da vida - a conservação garante nosso futuro!"],
      energy: ["Lâmpadas LED usam 75% menos energia!", "Painéis solares podem reduzir contas de luz de 50% a 100%!", "A energia eólica poderia alimentar o mundo 18 vezes!", "Desconectar dispositivos quando não estão em uso economiza 10%!", "Eletrodomésticos eficientes podem cortar contas em 30%!", "Energia renovável cria 3x mais empregos!", "Uma turbina eólica pode alimentar até 500 casas!", "Termostatos inteligentes podem economizar 10-15% em aquecimento!", "A energia solar é a fonte que mais cresce no mundo!", "Baterias são a chave para armazenar energia limpa!"],
      forest: ["Florestas abrigam 80% da biodiversidade terrestre!", "Uma árvore pode absorver cerca de 22 kg de CO2 por ano!", "Perdemos 10 milhões de hectares de floresta por ano!", "Plantar árvores é uma das formas mais eficazes de combater as mudanças climáticas!", "Florestas fornecem oxigênio, água limpa e habitat!", "O bambu pode crescer até 1 metro em 24 horas!", "A restauração florestal pode recuperar a biodiversidade em décadas!", "Florestas antigas armazenam mais carbono que florestas jovens!", "Papel reciclado economiza 17 árvores por tonelada!", "Proteger florestas é proteger nosso futuro!"]
    },
    localMultiplayer: { title: "Jogo Local", localPlay: "Jogo Local (Bluetooth/WiFi)", description: "Jogue com amigos próximos usando Bluetooth ou WiFi Direct - sem internet!", hostGame: "Criar Jogo", hostDescription: "Crie um jogo e aguarde amigos", findGame: "Encontrar Jogo", findDescription: "Procure jogos próximos", searching: "Procurando jogos próximos...", tapToJoin: "Toque para entrar", noGamesFound: "Nenhum jogo encontrado", noGamesHint: "Certifique-se de que o jogo do anfitrião está rodando", permissionRequired: "Permissão Necessária", permissionMessage: "Permissões de Bluetooth e localização são necessárias.", lobby: "Lobby do Jogo", waitingRoom: "Sala de Espera", waitingForPlayers: "Aguardando jogadores...", settingUp: "Configurando...", connectedToHost: "Conectado ao anfitrião", connecting: "Conectando...", players: "Jogadores", you_host: "Você (Anfitrião)", you: "Você", disconnected: "Desconectado", gameSettings: "Configurações do Jogo", startGame: "Iniciar Jogo", waitingForHost: "Aguardando o anfitrião...", waitForPlayers: "Aguardar Jogadores", needOnePlayer: "Pelo menos um jogador precisa entrar.", showScoreboard: "Placar", hideScoreboard: "Esconder", results: "Resultados", gameOver: "Fim de Jogo!", noResults: "Sem resultados disponíveis", playAgain: "Jogar Novamente", backToMenu: "Voltar ao Menu", hardwareReminder: "Certifique-se de que Wi-Fi, Bluetooth e Localização estão ativados." }
  }
};

// Write each language file
for (const [code, data] of Object.entries(translations)) {
  const filePath = path.join(localesDir, `${code}.json`);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 4), 'utf8');
  console.log(`Created ${code}.json (${JSON.stringify(data).length} bytes)`);
}

console.log('Done! Created ' + Object.keys(translations).length + ' language files');
