const fs = require('fs');
const path = require('path');
const localesDir = path.join(__dirname, '..', 'src', 'locales');
const en = JSON.parse(fs.readFileSync(path.join(localesDir, 'en.json'), 'utf8'));

const langs = {
  uk: { common:{loading:"Завантаження...",score:"Рахунок",moves:"Ходи",level:"Рівень",stars:"Зірки",back:"Назад",next:"Далі",close:"Закрити",resume:"Продовжити",restart:"Перезапуск",quit:"Вийти",yes:"Так",no:"Ні",ok:"ОК",cancel:"Скасувати",save:"Зберегти",settings:"Налаштування","new":"Новий","continue":"Продовжити",bestScore:"Найкращий рахунок",best:"Найкращий",tapToSkip:"Натисніть щоб пропустити",exitApp:"Вийти з додатку",exitConfirm:"Ви впевнені, що хочете вийти?",time:"Час",error:"Помилка"}, menu:{storyMode:"Режим історії",endlessMode:"Нескінченний режим",multiplayer:"Мультиплеєр",achievements:"Досягнення",leaderboard:"Таблиця лідерів",settings:"Налаштування",selectLevel:"Обрати рівень",selectTheme:"Обрати тему",tagline:"Врятуй планету, одна комбінація за раз"}, themes:{trashSorting:"Сортування сміття",trashSortingDesc:"Навчіться сортувати!",pollution:"Очистіть повітря",pollutionDesc:"Видаліть забруднюючі автомобілі!",waterConservation:"Збереження води",waterConservationDesc:"Заощаджуйте воду!",energyEfficiency:"Енергоефективність",energyEfficiencyDesc:"Використовуйте чисту енергію!",deforestation:"Збережіть ліси",deforestationDesc:"Садіть дерева!"} },
  tl: { common:{loading:"Naglo-load...",score:"Puntos",moves:"Galaw",level:"Antas",stars:"Bituin",back:"Bumalik",next:"Susunod",close:"Isara",resume:"Ipagpatuloy",restart:"I-restart",quit:"Umalis",yes:"Oo",no:"Hindi",ok:"OK",cancel:"Kanselahin",save:"I-save",settings:"Mga Setting","new":"Bago","continue":"Magpatuloy",bestScore:"Pinakamataas",best:"Pinakamahusay",tapToSkip:"I-tap para laktawan",exitApp:"Lumabas sa App",exitConfirm:"Sigurado ka bang gusto mong lumabas?",time:"Oras",error:"Error"}, menu:{storyMode:"Story Mode",endlessMode:"Walang Katapusang Mode",multiplayer:"Multiplayer",achievements:"Mga Achievement",leaderboard:"Leaderboard",settings:"Mga Setting",selectLevel:"Pumili ng Antas",selectTheme:"Pumili ng Tema",tagline:"Iligtas ang planeta, isang tugma sa isang pagkakataon"}, themes:{trashSorting:"Pag-uuri ng Basura",trashSortingDesc:"Matutong mag-recycle!",pollution:"Linisin ang Hangin",pollutionDesc:"Alisin ang mga sasakyang nagpopolusyon!",waterConservation:"Pag-iingat ng Tubig",waterConservationDesc:"Magtipid ng tubig!",energyEfficiency:"Kahusayan sa Enerhiya",energyEfficiencyDesc:"Gumamit ng malinis na enerhiya!",deforestation:"Iligtas ang mga Kagubatan",deforestationDesc:"Magtanim ng puno!"} },
  sw: { common:{loading:"Inapakia...",score:"Alama",moves:"Hatua",level:"Kiwango",stars:"Nyota",back:"Rudi",next:"Ifuatayo",close:"Funga",resume:"Endelea",restart:"Anza upya",quit:"Ondoka",yes:"Ndiyo",no:"Hapana",ok:"Sawa",cancel:"Ghairi",save:"Hifadhi",settings:"Mipangilio","new":"Mpya","continue":"Endelea",bestScore:"Alama bora",best:"Bora",tapToSkip:"Gusa kuruka",exitApp:"Toka Programu",exitConfirm:"Una uhakika unataka kutoka?",time:"Muda",error:"Hitilafu"}, menu:{storyMode:"Hali ya Hadithi",endlessMode:"Hali Isiyo na Mwisho",multiplayer:"Wachezaji wengi",achievements:"Mafanikio",leaderboard:"Ubao wa Viongozi",settings:"Mipangilio",selectLevel:"Chagua Kiwango",selectTheme:"Chagua Mandhari",tagline:"Okoa sayari, mechi moja kwa wakati"}, themes:{trashSorting:"Kupanga Taka",trashSortingDesc:"Jifunze kupanga!",pollution:"Safisha Hewa",pollutionDesc:"Ondoa magari yanayochafua!",waterConservation:"Uhifadhi wa Maji",waterConservationDesc:"Okoa maji!",energyEfficiency:"Ufanisi wa Nishati",energyEfficiencyDesc:"Tumia nishati safi!",deforestation:"Okoa Misitu",deforestationDesc:"Panda miti!"} },
  ro: { common:{loading:"Se încarcă...",score:"Scor",moves:"Mutări",level:"Nivel",stars:"Stele",back:"Înapoi",next:"Următorul",close:"Închide",resume:"Continuă",restart:"Repornește",quit:"Ieși",yes:"Da",no:"Nu",ok:"OK",cancel:"Anulează",save:"Salvează",settings:"Setări","new":"Nou","continue":"Continuă",bestScore:"Cel mai bun scor",best:"Cel mai bun",tapToSkip:"Apasă pentru a trece",exitApp:"Ieși din Aplicație",exitConfirm:"Ești sigur că vrei să ieși?",time:"Timp",error:"Eroare"}, menu:{storyMode:"Modul Poveste",endlessMode:"Modul Nesfârșit",multiplayer:"Multiplayer",achievements:"Realizări",leaderboard:"Clasament",settings:"Setări",selectLevel:"Selectează Nivel",selectTheme:"Selectează Tema",tagline:"Salvează planeta, un meci la un moment dat"}, themes:{trashSorting:"Sortarea Gunoiului",trashSortingDesc:"Învață să reciclezi!",pollution:"Curăță Aerul",pollutionDesc:"Elimină vehiculele poluante!",waterConservation:"Conservarea Apei",waterConservationDesc:"Economisește apa!",energyEfficiency:"Eficiența Energetică",energyEfficiencyDesc:"Folosește energie curată!",deforestation:"Salvează Pădurile",deforestationDesc:"Plantează copaci!"} },
  cs: { common:{loading:"Načítání...",score:"Skóre",moves:"Tahy",level:"Úroveň",stars:"Hvězdy",back:"Zpět",next:"Další",close:"Zavřít",resume:"Pokračovat",restart:"Restart",quit:"Ukončit",yes:"Ano",no:"Ne",ok:"OK",cancel:"Zrušit",save:"Uložit",settings:"Nastavení","new":"Nový","continue":"Pokračovat",bestScore:"Nejlepší skóre",best:"Nejlepší",tapToSkip:"Klepněte pro přeskočení",exitApp:"Ukončit aplikaci",exitConfirm:"Opravdu chcete odejít?",time:"Čas",error:"Chyba"}, menu:{storyMode:"Příběhový režim",endlessMode:"Nekonečný režim",multiplayer:"Více hráčů",achievements:"Úspěchy",leaderboard:"Žebříček",settings:"Nastavení",selectLevel:"Vybrat úroveň",selectTheme:"Vybrat téma",tagline:"Zachraňte planetu, jeden tah za druhým"}, themes:{trashSorting:"Třídění odpadu",trashSortingDesc:"Naučte se třídit!",pollution:"Vyčistěte vzduch",pollutionDesc:"Odstraňte znečišťující vozidla!",waterConservation:"Šetření vodou",waterConservationDesc:"Šetřete vodou!",energyEfficiency:"Energetická účinnost",energyEfficiencyDesc:"Používejte čistou energii!",deforestation:"Zachraňte lesy",deforestationDesc:"Sázejte stromy!"} },
  hu: { common:{loading:"Betöltés...",score:"Pontszám",moves:"Lépések",level:"Szint",stars:"Csillagok",back:"Vissza",next:"Következő",close:"Bezárás",resume:"Folytatás",restart:"Újraindítás",quit:"Kilépés",yes:"Igen",no:"Nem",ok:"OK",cancel:"Mégse",save:"Mentés",settings:"Beállítások","new":"Új","continue":"Folytatás",bestScore:"Legjobb pontszám",best:"Legjobb",tapToSkip:"Koppintson a kihagyáshoz",exitApp:"Kilépés az alkalmazásból",exitConfirm:"Biztosan ki akar lépni?",time:"Idő",error:"Hiba"}, menu:{storyMode:"Történet mód",endlessMode:"Végtelen mód",multiplayer:"Többjátékos",achievements:"Eredmények",leaderboard:"Ranglista",settings:"Beállítások",selectLevel:"Szint kiválasztása",selectTheme:"Téma kiválasztása",tagline:"Mentsd meg a bolygót, egy párosítás egyszerre"}, themes:{trashSorting:"Hulladék válogatás",trashSortingDesc:"Tanulj meg szelektálni!",pollution:"Tisztítsd meg a levegőt",pollutionDesc:"Távolítsd el a szennyező járműveket!",waterConservation:"Víztakarékosság",waterConservationDesc:"Takarékoskodj a vízzel!",energyEfficiency:"Energiahatékonyság",energyEfficiencyDesc:"Használj tiszta energiát!",deforestation:"Mentsd meg az erdőket",deforestationDesc:"Ültess fákat!"} },
  el: { common:{loading:"Φόρτωση...",score:"Σκορ",moves:"Κινήσεις",level:"Επίπεδο",stars:"Αστέρια",back:"Πίσω",next:"Επόμενο",close:"Κλείσιμο",resume:"Συνέχεια",restart:"Επανεκκίνηση",quit:"Έξοδος",yes:"Ναι",no:"Όχι",ok:"OK",cancel:"Ακύρωση",save:"Αποθήκευση",settings:"Ρυθμίσεις","new":"Νέο","continue":"Συνέχεια",bestScore:"Καλύτερο σκορ",best:"Καλύτερο",tapToSkip:"Πατήστε για παράλειψη",exitApp:"Έξοδος από την Εφαρμογή",exitConfirm:"Είστε σίγουροι ότι θέλετε να βγείτε;",time:"Χρόνος",error:"Σφάλμα"}, menu:{storyMode:"Λειτουργία Ιστορίας",endlessMode:"Ατέρμονη Λειτουργία",multiplayer:"Πολλοί Παίκτες",achievements:"Επιτεύγματα",leaderboard:"Πίνακας Κατάταξης",settings:"Ρυθμίσεις",selectLevel:"Επιλογή Επιπέδου",selectTheme:"Επιλογή Θέματος",tagline:"Σώστε τον πλανήτη, ένα ταίριασμα τη φορά"}, themes:{trashSorting:"Διαλογή Απορριμμάτων",trashSortingDesc:"Μάθετε να ανακυκλώνετε!",pollution:"Καθαρίστε τον Αέρα",pollutionDesc:"Αφαιρέστε τα ρυπογόνα οχήματα!",waterConservation:"Εξοικονόμηση Νερού",waterConservationDesc:"Εξοικονομήστε νερό!",energyEfficiency:"Ενεργειακή Απόδοση",energyEfficiencyDesc:"Χρησιμοποιήστε καθαρή ενέργεια!",deforestation:"Σώστε τα Δάση",deforestationDesc:"Φυτέψτε δέντρα!"} },
  he: { common:{loading:"...טוען",score:"ניקוד",moves:"מהלכים",level:"שלב",stars:"כוכבים",back:"חזרה",next:"הבא",close:"סגור",resume:"המשך",restart:"התחל מחדש",quit:"צא",yes:"כן",no:"לא",ok:"אישור",cancel:"ביטול",save:"שמור",settings:"הגדרות","new":"חדש","continue":"המשך",bestScore:"ניקוד הכי טוב",best:"הכי טוב",tapToSkip:"הקש כדי לדלג",exitApp:"יציאה מהאפליקציה",exitConfirm:"?האם אתה בטוח שברצונך לצאת",time:"זמן",error:"שגיאה"}, menu:{storyMode:"מצב סיפור",endlessMode:"מצב אינסופי",multiplayer:"מרובה משתתפים",achievements:"הישגים",leaderboard:"טבלת מובילים",settings:"הגדרות",selectLevel:"בחר שלב",selectTheme:"בחר נושא",tagline:"הצילו את כדור הארץ, התאמה אחת בכל פעם"}, themes:{trashSorting:"מיון פסולת",trashSortingDesc:"!למדו למיין",pollution:"נקו את האוויר",pollutionDesc:"!הסירו רכבים מזהמים",waterConservation:"שימור מים",waterConservationDesc:"!חסכו במים",energyEfficiency:"יעילות אנרגטית",energyEfficiencyDesc:"!השתמשו באנרגיה נקייה",deforestation:"הצילו את היערות",deforestationDesc:"!נטעו עצים"} },
  da: { common:{loading:"Indlæser...",score:"Score",moves:"Træk",level:"Niveau",stars:"Stjerner",back:"Tilbage",next:"Næste",close:"Luk",resume:"Genoptag",restart:"Genstart",quit:"Afslut",yes:"Ja",no:"Nej",ok:"OK",cancel:"Annuller",save:"Gem",settings:"Indstillinger","new":"Ny","continue":"Fortsæt",bestScore:"Bedste score",best:"Bedste",tapToSkip:"Tryk for at springe over",exitApp:"Luk appen",exitConfirm:"Er du sikker på, at du vil afslutte?",time:"Tid",error:"Fejl"}, menu:{storyMode:"Historietilstand",endlessMode:"Uendelig tilstand",multiplayer:"Flerspiller",achievements:"Præstationer",leaderboard:"Rangliste",settings:"Indstillinger",selectLevel:"Vælg niveau",selectTheme:"Vælg tema",tagline:"Red planeten, ét match ad gangen"}, themes:{trashSorting:"Affaldssortering",trashSortingDesc:"Lær at sortere!",pollution:"Rens luften",pollutionDesc:"Fjern forurenende køretøjer!",waterConservation:"Vandbesparelse",waterConservationDesc:"Spar på vandet!",energyEfficiency:"Energieffektivitet",energyEfficiencyDesc:"Brug ren energi!",deforestation:"Red skovene",deforestationDesc:"Plant træer!"} },
  fi: { common:{loading:"Ladataan...",score:"Pisteet",moves:"Siirrot",level:"Taso",stars:"Tähdet",back:"Takaisin",next:"Seuraava",close:"Sulje",resume:"Jatka",restart:"Aloita alusta",quit:"Lopeta",yes:"Kyllä",no:"Ei",ok:"OK",cancel:"Peruuta",save:"Tallenna",settings:"Asetukset","new":"Uusi","continue":"Jatka",bestScore:"Paras tulos",best:"Paras",tapToSkip:"Napauta ohittaaksesi",exitApp:"Sulje sovellus",exitConfirm:"Haluatko varmasti poistua?",time:"Aika",error:"Virhe"}, menu:{storyMode:"Tarinatila",endlessMode:"Loputon tila",multiplayer:"Moninpeli",achievements:"Saavutukset",leaderboard:"Tulostaulu",settings:"Asetukset",selectLevel:"Valitse taso",selectTheme:"Valitse teema",tagline:"Pelasta planeetta, yksi yhdistelmä kerrallaan"}, themes:{trashSorting:"Jätteiden lajittelu",trashSortingDesc:"Opi lajittelemaan!",pollution:"Puhdista ilma",pollutionDesc:"Poista saastuttavat ajoneuvot!",waterConservation:"Vedensäästö",waterConservationDesc:"Säästä vettä!",energyEfficiency:"Energiatehokkuus",energyEfficiencyDesc:"Käytä puhdasta energiaa!",deforestation:"Pelasta metsät",deforestationDesc:"Istuta puita!"} }
};

for (const [code, data] of Object.entries(langs)) {
  const full = JSON.parse(JSON.stringify(en));
  for (const [section, vals] of Object.entries(data)) {
    full[section] = { ...full[section], ...vals };
  }
  fs.writeFileSync(path.join(localesDir, `${code}.json`), JSON.stringify(full, null, 4), 'utf8');
  console.log(`Created ${code}.json`);
}
console.log('Done! Created ' + Object.keys(langs).length + ' files');
